from .nodes.material_inspector import NODE_CLASS_MAPPINGS as MATERIAL_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MATERIAL_DISPLAY_MAPPINGS
from .nodes.mesh_transform import NODE_CLASS_MAPPINGS as TRANSFORM_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TRANSFORM_DISPLAY_MAPPINGS
from .nodes.scene_assembler import NODE_CLASS_MAPPINGS as ASSEMBLER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ASSEMBLER_DISPLAY_MAPPINGS
from .nodes.mesh_loader import NODE_CLASS_MAPPINGS as LOADER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **MATERIAL_CLASS_MAPPINGS,
    **TRANSFORM_CLASS_MAPPINGS,
    **ASSEMBLER_CLASS_MAPPINGS,
    **LOADER_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MATERIAL_DISPLAY_MAPPINGS,
    **TRANSFORM_DISPLAY_MAPPINGS,
    **ASSEMBLER_DISPLAY_MAPPINGS,
    **LOADER_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
